iterToViz = 3
studyPt_prm.vecXSecret = funcPrm.x0;
tic();
p = studyPt( ...
  grootDatOut.funchF, ...
  grootDatOut.iterDat(iterToViz).vecX, ...
  grootDatOut.iterDat(iterToViz).matI, ...
  grootDatOut.iterDat(iterToViz).matJ, ...
  studyPt_prm );
toc();
