if ( isempty(prev_vecX) )
	msg( __FILE__, __LINE__, sprintf( ...
	  "  %8s, %8s, %8s;  %8s, %9s;  %8s, %9s;  %s", ...
	  "time", ...
	  "iter", ...
	  "|deltaX|", ...
	  "fBest", ...
	  "fB fall", ...
	  "|gBest|", ...
	  "|gB|fall", ...
	  "fevalCount" ) );
	  %
	msg( __FILE__, __LINE__, sprintf( ...
	  "  %8.2e, %8d, %8.2e;  %8.2e, %9.2e;  %8.2e, %9.2e;  %d", ...
	  time()-startTime, ...
	  iterCount, ...
	  0.0, ... % norm(prev_vecXBest - vecXBest)
	  f, ...
	  0.0, ... % prev_fBest - fBest
	  norm(vecG), ...
	  0.0, ... % norm(prev_vecGBest) - norm(vecGBest)
	  fevalCount ) );
else
	msg( __FILE__, __LINE__, sprintf( ...
	  "  %8.2e, %8d, %8.2e;  %8.2e, %9.2e;  %8.2e, %9.2e;  %d", ...
	  time()-startTime, ...
	  iterCount, ...
	  norm(prev_vecX - vecX), ...
	  f, ...
	  prev_f - f, ...
	  norm(vecG), ...
	  norm(prev_vecG) - norm(vecG), ...
	  fevalCount ) );
	
endif
