numFigs = 0;

numFigs++; figure(numFigs);
plot( ...
  viz_xVals, viz_fVals, 'o-', 'markersize', 3, ...
  xVals, fVals, '+', 'linewidth', 5, 'markersize', 30, ...
  bigX, funchF(bigX), '*', 'linewidth', 4, 'markersize', 25, ...
  xOfCand*[1,1], [min(viz_fVals),max(viz_fVals)], ...
  '-', 'linewidth', 4, 'markersize', 25 );
grid on;

x = viz_xVals;
f = viz_fVals;
cx = cent(x);
df = diff(f)./diff(x);
cdf = cent(df);
ccx = cent(cx);
ddf = diff(df)./diff(cx);
cch = cdf./ddf;


numFigs++; figure(numFigs);
plot( ...
  ccx, cch, 'o-', 'markersize', 3, ...
  [ccx(1),ccx(end)], [cch(1),cch(end)], '-', 'markersize', 3, ...
  datOut.xValsForH, datOut.hVals, '+-', 'linewidth', 5, 'markersize', 30, ...
  datOut.xValsLoForH, datOut.hVals, 'o-', 'linewidth', 3, 'markersize', 20, ...
  datOut.xValsHiForH, datOut.hVals, 'o-', 'linewidth', 3, 'markersize', 20, ...
  bigX, 0.0, '*', 'linewidth', 4, 'markersize', 25, ...
  xVals, 0*xVals, 'k-' );
grid on;
