clear;
tic();
commondefs;
figIndex = 0;
%
xVals = linspace(-1.0,1.0,26);
yVals = linspace( 0.0,1.0,21);
[ gridX, gridY ] = ndgrid( xVals, yVals );
gridF = (gridX.*gridY)+(gridX.^2);
%gridF = gridX;
%
numCuts = 50;
colorMap_base = 0.4 + (jet(1000)*0.4);
fMin_base =  0.0;
fMax_base =  1.0;
color_underMin = [0.2,0.2,0.2];
color_overMax  = [0.9,0.9,0.9];
fVals_flagged = [0.4;0.6];
colorMap_flagged = [0.0,1.0,1.0;1.0,0.0,1.0];
funchZ = @(f)(f);
%funchZ = @(f)(asinh(100*f)/100);
strContourFunc = "contourf";
strColorbarFunc = "colorbarf";
%
figIndex++; figure(figIndex);
mycontour( ...
  gridX, ...
  gridY, ...
  gridF, ...
  numCuts, ...
  colorMap_base, ...
  fMin_base, ...
  fMax_base, ...
  color_underMin, ...
  color_overMax, ...
  fVals_flagged, ...
  colorMap_flagged, ...
  funchZ, ...
  strContourFunc );
axis([ -1.5, 1.5, -0.5, 1.5]);
%
figIndex++; figure(figIndex);
mycontour( ...
  gridX, ...
  gridY, ...
  gridF, ...
  numCuts, ...
  colorMap_base, ...
  fMin_base, ...
  fMax_base, ...
  color_underMin, ...
  color_overMax, ...
  fVals_flagged, ...
  colorMap_flagged, ...
  funchZ, ...
  strColorbarFunc );
%
toc();
