jevalDriver.exe : jevalDriver.o
	g++ -o jevalDriver.exe jevalDriver.o

jevalDriver.o : jevalDriver.cpp
	g++ -c jevalDriver.cpp

proxyPIES.exe : proxyPIES.o
	g++ -o proxyPIES.exe proxyPIES.o

proxyPIES.o : proxyPIES.cpp
	g++ -c proxyPIES.cpp

clean :
	rm jevalDriver.exe jevalDriver.o proxyPIES.exe proxyPIES.o
