msg( __FILE__, __LINE__, sprintf( "   %10.3e (/%0.3e); %5d (/%d); %8d (/%d):  %10.3e (/%0.3e);  %10.3e, %10.3e (/%0.3e);  %10.3e (/%0.3e)", ...
  time() - startTime, ...
  prm.timeLimit, ...
  iterCount,
  prm.iterLimit, ...
  fevalCount, ...
  prm.fevalLimit, ...
  norm( vecXHarvest - vecXSeed ), ...
  prm.xTol, ...
  superPt_f, ...
  -1.0, %superPt_fPrev - superPt_f, ...
  prm.fTol, ...
  norm(superPt_vecG), ...
  prm.gTol ) );
