%  Function...
%    msgnnl( fileName, lineNum, msgStr )
%  Overview...
%    Part of myutil module.
%    My formatted alternative to printf().
%    Adds customized information such as fileName, lineNum, and current time.
%    Does NOT put a newline at the end of output.
%  Input values...
%    fileName: Name of file from which called, ideally __FILE__.
%    lineNum: Line number from which called, ideally __LINE__.
%    msgStr: The message content.
%
%  IMPORTANT NOTE!!!
%   On Octave 3.8.1 and earlier,
%   "__FILE__" is likely to cause Octave to crash;
%   Here, unfortunately, it may be necessary to use some "thisFile",
%   a la, 'thisFile = foo.m'; 'msg( thisFile, __LINE__, "Hello world!" );' instead.
function msgnnl( fileName, lineNum, msgStr )
	clockNow = clock();
	printf( "%02d:%02d:%02d.%03d [%s.%d] %s", ...
	  clockNow(4), ...
	  clockNow(5), ...
	  floor(clockNow(6)), ...
	  floor(1000*(clockNow(6) - floor(clockNow(6)) )), ...
	  fileName, ...
	  lineNum, ...
	  msgStr );
return;
end
