function msgretcodeif( cond, fileName, lineNum, retCode )
	if ( 4 ~= nargin )
		msg( __FILE__, __LINE__, "Invalid number of arguments." );
		print_usage();
		return; % Superfluous?
	end
	if (~cond)
		return;
	end
	msgStr = sprintf( "Passing return code %s.", retcode2str(retCode) );
	clockNow = clock();
	printf( "%02d:%02d:%02d.%03d [%s %4d]  %s\n", ...
	  clockNow(4), ...
	  clockNow(5), ...
	  floor(clockNow(6)), ...
	  floor(1000*(clockNow(6) - floor(clockNow(6)) )), ...
	  trimFileName(fileName), ...
	  lineNum, ...
	  msgStr );
return;
end
