%function mycontour( ...
%  gridX, ...
%  gridY, ...
%  gridF, ...
%  fLo = min(min(gridF)), ...
%  fHi = max(max(gridF)), ...
%  cMapFull = mycmap, ...
%  funchViz = @(f)(f), ...
%  numCL = 20, ...
%  fFlagVals = [], ...
%  prm = [] )

function mycontour( ...
  gridX, ...
  gridY, ...
  gridF, ...
  fLo = min(min(gridF)), ...
  fHi = max(max(gridF)), ...
  cMapFull = mycmap, ...
  funchViz = @(f)(f), ...
  numCL = 20, ...
  fFlagVals = [], ...
  prm = [] )
	%
	vLo = funchViz(fLo);
	vHi = funchViz(fHi);
	gridV = cap(funchViz(gridF),vLo,vHi);
	v0 = min(min(gridV));
	v1 = max(max(gridV));
	%
	numCFull = size(cMapFull,1);
	i0 = 1 + floor( (numCFull-1.0)*(v0-vLo)/(vHi-vLo) + sqrt(eps) );
	i1 = 1 + ceil( (numCFull-1.0)*(v1-vLo)/(vHi-vLo) - sqrt(eps) );
	cMap = cMapFull(i0:i1,:);
	%
	contourf( gridX, gridY, gridV, numCL );
	colormap(cMap);
	grid on;
return;
end
