clear;
commondefs;
thisFile = "test_getLLMCurvs";
%
vecF = [-2;-3];
matJ = [-1,1;1,5];
matV = eye(2,2);
matW = matJ*matV;
numPts = 50;
%
prm.curveTypes = [ ...
  STEPTYPE__NEWTON, ...
  STEPTYPE__PICARD, ...
  STEPTYPE__PICARD_SCALED, ...
  STEPTYPE__GRADDIR, ...
  STEPTYPE__GRADDIR_SCALED, ...
  STEPTYPE__LEVCURVE, ...
  STEPTYPE__LEVCURVE_SCALED, ...
  STEPTYPE__GRADCURVE, ...
  STEPTYPE__GRADCURVE_SCALED ];
[ curveDat, retCode, datOut ] = getLLMCurves( vecF, matV, matW, numPts );
