function vizPt_curve2d_colorbar( studyPtDat, indexB1, indexB2, strContour="omega", prm=[], datIn=[] )
	%
	%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
	% COMMON INIT.
	%
	commoninit;
	thisFile = "vizPt_curve2d_colorbar";
	%
	%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
	% INIT.
	%
	funchZ = @(omega)( omega.^0.5 );
	numCol_colorbar = 30;
	%
	omegaLo = studyPtDat.omegaLo
	omega0 = studyPtDat.omega0
	omegaVizMin = 0.0
	omegaVizMax = 2.0*omega0
	%
	%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
	% DO WORK.
	%
	if (1)
		xVals = (0:1);
		yVals = linspace( 0, omegaVizMax, numCol_colorbar );
		[ gridX, gridY ] = ndgrid(xVals,yVals);
		gridO = gridY;
		%
		vizPt_curve2d_contour( ...
		  gridX, ...
		  funchZ(gridY), ...
		  gridO, ...
		  numCol_colorbar, ...
		  omegaVizMin, ...
		  omegaLo, ...
		  omega0, ...
		  omegaVizMax, ...
		  funchZ, ...
		  "contourf" );
		%
		set(get(gcf,"children"),"xticklabel",[]);
		grid on;
		ylabel( "value" );
		title( "colorbar (funchZ)" );
		return;
	else
		xVals = (0:1);
		yVals = linspace( ...
		  -omega0/numCol_colorbar, ...
		  omegaVizMax + (omega0/numCol_colorbar), ...
		   numCol_colorbar );
		[ gridX, gridY ] = ndgrid(xVals,yVals);
		gridO = gridY;
		%
		vizPt_curve2d_contour( ...
		  gridX, ...
		  gridY, ...
		  gridO, ...
		  numCol_colorbar, ...
		  omegaVizMin, ...
		  omegaLo, ...
		  omega0, ...
		  omegaVizMax, ...
		  @(omega_dummy)( (omega_dummy) ), ...
		  "contourf" );
		%
		set(get(gcf,"children"),"xticklabel",[]);
		grid on;
		ylabel( "value" );
		title( "colorbar (original values)" );
		return;
	end
return;
end

