numFigs = 0;
tic();
%
matAbsF = abs(matF);
matFSq = matF.^2;
%
avgFVals = sum(matF,1)/numTrials;
avgAbsFVals = sum(matAbsF,1)/numTrials;
avgFSqVals = sum(matFSq,1)/numTrials;
%
fracAbsFLE3E0 = sum( double(matAbsF<=3E0), 1 )/numTrials;
fracAbsFLE1E0 = sum( double(matAbsF<=1E0), 1 )/numTrials;
fracAbsFLE1EM1 = sum( double(matAbsF<=1E-1), 1 )/numTrials;
fracAbsFLE1EM2 = sum( double(matAbsF<=1E-2), 1 )/numTrials;
%
numFigs++; figure(numFigs);
plot( ...
 xVals, abs(avgFVals), 'o-', ...
 xVals, avgAbsFVals, 'x-', ...
 xVals, sqrt(avgFSqVals), '^-' );
grid on;
%
numFigs++; figure(numFigs);
plot( ...
 cent(xVals), diff(abs(avgFVals))./diff(xVals), 'o-', ...
 cent(xVals), diff(avgAbsFVals)./diff(xVals), 'x-', ...
 cent(xVals), diff(sqrt(avgFSqVals))./diff(xVals), '^-' );
grid on;
%
numFigs++; figure(numFigs);
plot( ...
 xVals, fracAbsFLE3E0, 's-', ...
 xVals, fracAbsFLE1E0, 'o-', ...
 xVals, fracAbsFLE1EM1, 'x-', ...
 xVals, fracAbsFLE1EM2, '^-' );
grid on;
%
numFigs++; figure(numFigs);
plot( ...
 cent(xVals), diff(fracAbsFLE3E0)./diff(xVals), 's-', ...
 cent(xVals), diff(fracAbsFLE1E0)./diff(xVals), 'o-', ...
 cent(xVals), diff(fracAbsFLE1EM1)./diff(xVals), 'x-', ...
 cent(xVals), diff(fracAbsFLE1EM2)./diff(xVals), '^-' );
grid on;
%
toc();
