clear;
tic();
commondefs;
%
xVals = linspace(-1.0,1.0,26);
yVals = linspace( 0.0,1.0,21);
[ gridX, gridY ] = ndgrid( xVals, yVals );
gridF = (gridX.*gridY)+(gridX.^2);
%gridF = gridX;
%
numCuts = 50;
colorMap_base = 0.4 + (jet(1000)*0.4);
fMin_base =  0.0;
fMax_base =  1.0;
color_underMin = [0.3,0.3,0.3];
color_overMax  = [0.8,0.8,0.8];
fVals_flagged = [];
colorMap_flagged = [];
funchZ = @(f)(f);
strContourFunc = "contourf";
%
mycontour( ...
  gridX, ...
  gridY, ...
  gridF, ...
  numCuts, ...
  colorMap_base, ...
  fMin_base, ...
  fMax_base, ...
  color_underMin, ...
  color_overMax, ...
  fVals_flagged, ...
  colorMap_flagged, ...
  funchZ, ...
  strContourFunc );
axis([ -1.5, 1.5, -0.5, 1.5]);
%
toc();