	STEP_TYPE__BLIND_NEWTON = 0;
	STEP_TYPE__BLIND_GRAD_MIN = 10;
	STEP_TYPE__SCAN_LEV_MIN = 100;
	%	
	JUPDATE_TYPE__NONE = 0;
	JUPDATE_TYPE__BROYDEN = 10;
	JUPDATE_TYPE__BROYDEN_ALT = 11; % Can behave differently (worse?) due to finite precision effects.
	JUPDATE_TYPE__SECANT_REORTHONORM = 20;
	JUPDATE_TYPE__LESQUJ_PRIMAL = 30;
	JUPDATE_TYPE__RECALC = 100;
